import pygame

TILES_WIDTH = 22
TILES_WIDTH2 = TILES_WIDTH/2
TILES_HEIGHT = 48
TILES_HEIGHT2 = TILES_HEIGHT/2

TILE_SIZE = 32
TILE_SIZE2 = TILE_SIZE/2
TILE_SIZE4 = TILE_SIZE/4

vec = pygame.math.Vector2 

VELOCITY = 1.2
VELOCITY_ANIMAL = 0.6